baseURL: https://harishronopoulos.netlify.app/
languageCode: en-us
title: Haris Hronopoulos
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I see someone is interested in me! Press "get started"" to get 
      to know more about me.
    title: Hi, my name is Haris
  blog: {}
  contact:
    address:
      - city: Athens,
        country: Greece
        street: Leoforos Alexandras, 13
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: harisc.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (133) 131-13131313
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Haris_Hronopoulos
    enable: yes
#    quicklinks:
#     - alt: HTML5 UP
#       text: 'Design: '
#       url: https://www.html5up.net
    social:
       - icon: fa-twitter
         label: Twitter
         url: https://twitter.com/HarryH42933680
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
       - icon: fa-github
         label: GitHub
         url: https://github.com/HarisHronopoulos
       - icon: fa-linkedin
         label: LinkedIn
         url: https://www.linkedin.com/in/haris-hronopoulos/
  image: ''
  name: Your name
  navigation:
#    button1:
#      - name: Get Started
#        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: CV
#        url: blogs/CV
#      - name: 
#       url: elements.htm
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic07.jpg
        subtitle: Extreme sports & meditation
        title: My passions
        url: blogs/Mypassions
      - image: pic11.jpg
#        subtitle: About me
        title: About me
        url: blogs/aboutme 
      - image: pic10.jpg
        subtitle: Data science projects
        title: Code
        url: blogs/code1
      - image: pic06.jpg
        subtitle: My work experience & education
        title: My CV
        url: blogs/CV
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
#  two:
#    buttonText:[My CV](https://drive.google.com/file/d/1gP3l8yoGFmbt9pyOBcBcoRoGqZKf84Qu/view?usp=sharing)
#    enable: yes
#    subtitle: "Want to know more about my work experience and education?"
#    title: My education & work experience
#    url: https://drive.google.com/file/d/1gP3l8yoGFmbt9pyOBcBcoRoGqZKf84Qu/view?usp=sharing
