baseURL: https://harishronopoulos.netlify.app/
languageCode: en-us
title: Haris Hronopoulos
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I see someone is interested in me! Press "get started"" to get 
      to know more about me.
    title: Hi, my name is Haris
  blog: {}
  contact:
    address:
      - city: Athens,
        country: Greece
        street: Leoforos Alexandras, 13
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: harisc.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (133) 131-13131313
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Haris Hronopoulos
    enable: yes
#    quicklinks:
 #     - alt: HTML5 UP
  #      text: 'Design: '
   #     url: https://www.html5up.net
    social:
       - icon: fa-twitter
         label: Twitter
         url: https://twitter.com/HarryH42933680
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/HarisHronopoulos
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/haris-hronopoulos/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: CV
        url: blogs/CV
#      - name: Elements
#       url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic07.jpg
        subtitle: Extreme sports & meditation
        title: My passions
        url: blogs/Mypassions
      - image: pic09.jpg
        subtitle: Work experience & education
        title: Curriculum vitae
        url: blogs/CV
      - image: pic10.jpg
        subtitle: Data science projects
        title: Code
        url: blogs/code
#      - image: pic10.jpg
#        subtitle: Nisl Sed Aliquam
#        title: Ipsum
#        url: blogs/ipsum
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
